//! Event Flows Example — Declarative event pipeline demo
//!
//! This example demonstrates the full this-rs event system:
//!
//! 1. **EventBus**: Real-time broadcast of all entity/link mutations
//! 2. **SSE endpoint**: `/events/stream` for real-time event consumption
//! 3. **Sinks**: In-app notification store (auto-wired from YAML config)
//! 4. **Flows**: Declarative pipelines (trigger → filter → map → deliver)
//! 5. **Notification REST API**: CRUD on stored notifications
//!
//! The event pipeline is auto-wired by the ServerBuilder:
//! - BillingModule provides entities/links config
//! - EventFlowsConfig provides events/sinks config (loaded from config/links.yaml)
//! - ServerBuilder merges both configs and auto-wires the full pipeline

use std::sync::Arc;

use anyhow::Result;
use axum::Router;
use tower_http::services::ServeDir;

use billing::{BillingModule, BillingStores};
use test_data::populate_test_data;

use this::config::LinksConfig;
use this::core::module::Module;
use this::core::{EntityCreator, EntityFetcher};
use this::server::builder::ServerBuilder;
use this::server::entity_registry::EntityRegistry;
use this::server::{RestExposure, WebSocketExposure};
use this::storage::InMemoryLinkService;

/// A config-only module that provides events/sinks configuration.
///
/// This is a minimal module — no entities, no stores — it only contributes
/// the `events:` and `sinks:` sections to the merged LinksConfig.
struct EventFlowsConfig;

impl Module for EventFlowsConfig {
    fn name(&self) -> &str {
        "event-flows"
    }

    fn version(&self) -> &str {
        "0.1.0"
    }

    fn entity_types(&self) -> Vec<&str> {
        vec![] // No entities — billing module provides those
    }

    fn register_entities(&self, _registry: &mut EntityRegistry) {
        // No entities to register — billing module handles those
    }

    fn links_config(&self) -> Result<LinksConfig> {
        // Load only the events/sinks config from our YAML
        let config_path = concat!(env!("CARGO_MANIFEST_DIR"), "/config/links.yaml");
        LinksConfig::from_yaml_file(config_path)
    }

    fn get_entity_fetcher(&self, _entity_type: &str) -> Option<Arc<dyn EntityFetcher>> {
        None
    }

    fn get_entity_creator(&self, _entity_type: &str) -> Option<Arc<dyn EntityCreator>> {
        None
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt::init();

    let stores = BillingStores::new_in_memory();
    let billing_module = BillingModule::new(stores);

    let link_service_arc = Arc::new(InMemoryLinkService::new());

    // Populate test data BEFORE building the host (builder consumes the link service)
    populate_test_data(&billing_module.stores, link_service_arc.clone()).await?;

    // Build the transport-agnostic host
    //
    // Two modules are registered:
    // 1. BillingModule     → provides entities (order, invoice, payment) + links
    // 2. EventFlowsConfig  → provides events (3 flows) + sinks (in-app)
    //
    // ServerBuilder merges both configs and auto-wires:
    // - EventBus (1024)      → real-time broadcast + SSE
    // - NotificationStore    → in-app notification storage
    // - SinkRegistry         → sink dispatch (in-app)
    // - EventLog (memory)    → persistent event storage
    //
    // Full pipeline: EventBus → EventLog → FlowRuntime → SinkRegistry → InAppSink
    let host = Arc::new(
        ServerBuilder::new()
            .with_link_service((*link_service_arc).clone())
            .with_event_bus(1024)
            .register_module(billing_module)?
            .register_module(EventFlowsConfig)?
            .build_host()?,
    );

    // Build REST + WebSocket routers
    // REST auto-includes:
    //   - SSE /events/stream (because EventBus is configured)
    //   - /notifications/:user_id/* (because NotificationStore is configured)
    let rest_router = RestExposure::build_router(host.clone(), vec![])?;
    let ws_router = WebSocketExposure::build_router(host.clone())?;

    // Serve static files (for the HTML test client)
    let static_files = ServeDir::new("examples/event-flows/static");

    let app = Router::new()
        .merge(rest_router)
        .merge(ws_router)
        .nest_service("/static", static_files);

    println!("\n🚀 Event Flows Example running on http://127.0.0.1:4245");
    println!("\n📚 Endpoints:");
    println!("\n  REST API (CRUD):");
    println!("    GET/POST   /orders");
    println!("    GET/POST   /invoices");
    println!("    GET/POST   /payments");
    println!("\n  Events (real-time):");
    println!("    GET        /events/stream          (SSE — Server-Sent Events)");
    println!("    WS         /ws                     (WebSocket)");
    println!("\n  Notifications (auto-generated by flows):");
    println!("    GET        /notifications/system");
    println!("    GET        /notifications/system/unread-count");
    println!("    POST       /notifications/system/read-all");
    println!("\n  Test client:");
    println!("    GET        /static/index.html");
    println!("\n💡 Quick test — create an order and see the notification:");
    println!();
    println!("   # 1. Watch events in real-time (in another terminal):");
    println!("   curl -N http://127.0.0.1:4245/events/stream");
    println!();
    println!("   # 2. Create an order (triggers notify-new-order flow):");
    println!(
        "   curl -X POST http://127.0.0.1:4245/orders -H 'Content-Type: application/json' \\"
    );
    println!("     -d '{{\"name\": \"Laptop Pro\", \"status\": \"pending\", \"owner_id\": \"system\"}}'");
    println!();
    println!("   # 3. Check the notification was created:");
    println!("   curl http://127.0.0.1:4245/notifications/system");
    println!();

    let listener = tokio::net::TcpListener::bind("127.0.0.1:4245").await?;
    axum::serve(listener, app).await?;

    Ok(())
}
